# Use root/example as user/password credentials
version: '3.1'

services:
  smtp4dev:
    container_name: smtp
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '8081:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '8025:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
